# 服务器配置
server:

  # 端口号码
  port: 8300

# Spring 配置
spring:

  # 数据源配置
  datasource:

    # 驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 连接地址
    url: jdbc:mysql://localhost:6033/spring_boot_mybatis_redis_demo?useSSL=false

    # 用户名称
    username: root

    # 密码
    password: 123456

  # Redis 配置
  redis:

    # 端口号码
    port: 8401

    # 密码
    password: 123456

# Mybatis 配置
mybatis:
  configuration:

    # 下换线转为驼峰
    map-underscore-to-camel-case: true

    # 枚举处理类
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
